import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/keybingings.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[scrolling]
multiplier = 2
